<?php
/*
	Esta transa��o destr�i a sess�o do usu�rio e exibe
	o formul�rio de login
*/

include("../../intranet/library/library.php");

setSession("sis_userid","");
setSession("sist_id","");
setSession("sis_username","");
setSession("sis_username_antiguo","");
setSession("sis_level","");
setSession("sis_depeid","");				
setSession("sis_apl","");
setSession("sis_persid","");
setSession("sis_pdlaid","");
setSession("sis_medi_id","");
setSession("sis_empresa_ruc","");
setSession("sis_iporigen","");
setSession("sis_depename","");
setSession("sis_depe_superior","");
setSession("SET_TODOS_USUARIOS","");
setSession("SET_TIPO_DESPACHO","");
setSession("SET_CERTIFICADO","");
setSession("SET_EMRU_EMISOR","");
setSession("SET_DEPE_COMPRAS_VENTAS","");
setSession("SET_VENT_ID","");
setSession("SET_APLICA_DESCUENTO","");
setSession("SET_EDITA_TOTAL","");
setSession("SET_EDITA_TOTAL2","");
setSession("SET_EDITA_IMPUNITARIO","");
setSession("SET_EDITA_FECHA","");
setSession("cadSearch","");
setSession("tipo_expediente","");
    
unset($_SESSION["sis_userid"]);
unset($_SESSION["sist_id"]);
unset($_SESSION["sis_username"]);
unset($_SESSION["sis_username_antiguo"]);
unset($_SESSION["sis_level"]);
unset($_SESSION["sis_depeid"]);
unset($_SESSION["sis_apl"]);
unset($_SESSION["sis_persid"]);
unset($_SESSION["sis_pdlaid"]);
unset($_SESSION["sis_iporigen"]);
unset($_SESSION["sis_depename"]);
unset($_SESSION["sis_medi_id"]);
unset($_SESSION["sis_empresa_ruc"]);
unset($_SESSION["sis_depe_superior"]);
unset($_SESSION["SET_ESJEFE"]);
unset($_SESSION["SET_AUTORIZA_SOLICITUD"]);
unset($_SESSION["SET_TODOS_USUARIOS"]);
unset($_SESSION["SET_TIPO_DESPACHO"]);
unset($_SESSION["SET_CERTIFICADO"]);
unset($_SESSION["SET_DEPE_EMISOR"]);
unset($_SESSION["SET_DEPE_EMISOR_EXCLUSIVO"]);
unset($_SESSION["SET_DEPE_COMPRAS_VENTAS"]);
unset($_SESSION["SET_VENT_ID"]);
unset($_SESSION["SET_APLICA_DESCUENTO"]);
unset($_SESSION["SET_EDITA_TOTAL"]);
unset($_SESSION["SET_EDITA_TOTAL2"]);
unset($_SESSION["SET_EDITA_IMPUNITARIO"]);
unset($_SESSION["SET_EDITA_FECHA"]);
unset($_SESSION["cadSearch"]);
unset($_SESSION["tipo_expediente"]);
redirect("index.php","top");